# Generated by Django 4.2.6 on 2023-10-26 19:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('other_books', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=30)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('synopsis', models.TextField()),
                ('year', models.IntegerField(default=0, null=True)),
                ('cover', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.author')),
            ],
        ),
    ]
