# Generated by Django 4.2.6 on 2023-11-05 23:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0006_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
