# Generated by Django 4.2.6 on 2023-11-14 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0007_list_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='shared_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
